### ISSUE TITLE
Issue after last update : Undefined index: title

### ISSUE THREAD

**Issue by lorajc** [adrenth/redirect#10]
When add or edit a redirect.

Undefined index: title
C:\wamp\www\dev\logimonde\plugins\adrenth\redirect\classes\OptionHelper.php line 43

`       /** @type Page $page */
        foreach ($pages as $page) {
            $options[$page->getFileName()] = sprintf(
                '%s - %s',
                $page->settings['title'],
                $page->settings['url']
            );
        }`

**Comment by adrenth** [comment]
Thanks for noticing! I'll release a fix for it today.

**Comment by adrenth** [comment]
This one is fixed in release 1.1.1
