### ISSUE TITLE
Subdomain redirects

### ISSUE THREAD

**Issue by goeroe** [adrenth/redirect#16]
Would subdomain redirects be something that could be managed by this plugin in the future?

For example:

Source path
/example/model/{category}

Target path
{category}.domain.com

**Comment by adrenth** [comment]
Yes, sure! I'll put it on my todo list. V2 is coming soon.

**Comment by adrenth** [comment]
Hi, goeroe. It just happens to work with version 2.0.0 :-)

Try this:

Target type: `Path or URL`
Path: `/foo/{bar}`
Target url: `http://{bar}.foo.com/`

Add one requirement:
Placeholder: `{bar}`
Requirement: `[a-zA-Z]+`

And that should work well.

**Comment by goeroe** [comment]
Is there a way to make it work the other way around?

Source path:
http://{{slug}.foo.com

Target type: I guess CMS page (in this case)
For example a user profile page

I was wrong when I assumed that this could be used as a workaround for octobercms not having the ability to have wildcard subdomains in the "url" parameter of a cms page. This only handles the redirect, not the actual route.

My bad :)
