### ISSUE TITLE
Import of 404 error log

### ISSUE THREAD

**Issue by pvullioud** [adrenth/redirect#17]
Could be great to have a way to import some 404 error from the request log.
We can imagine a popup with a search field and all the 404 and a way to select them.

**Comment by adrenth** [comment]
That's a really great idea. I will look into it.

**Comment by pvullioud** [comment]
Hi,
Thanks for the feedback. One nice way could be to add a button in the Request log like
<img src="https://monosnap.com/file/YQUJG9D0WmTlFyfqGXDrpkECIoz5UG.png">

**Comment by adrenth** [comment]
I already have a implementation that almost works :-) I've added a button "Request Log" to the button toolbar. When this button is clicked, it opens a modal view with a (custom) Request Log list. 

<img width="650" alt="screen shot 2016-07-08 at 14 17 46" src="https://cloud.githubusercontent.com/assets/5699988/16687144/05d67d08-4517-11e6-8c90-c4ab4973f465.png">

<img width="1266" alt="screen shot 2016-07-08 at 14 17 36" src="https://cloud.githubusercontent.com/assets/5699988/16687134/fcecb888-4516-11e6-9aaa-0bca76212b73.png">

So, now it is possible to select a Request Log item and create a redirect for it. But I need more data to create a valid redirect. Or we can choose to make it disabled by default and let the user fill in the blanks and manually enable it.

I think we can add some more functionality here or create a second step where you can specify more details for the redirect to create.

If you have any suggestions on what to do after you've selected the log item, please let me know.

And maybe you can describe how you'd like it to work. All suggestions are welcome.

Great feature request.

**Comment by pvullioud** [comment]
Hi,
You are  the speedy Gonzales of OctoberCMS ;)
Your implementations looks great.
Import and disabled by default it's great for a first step.

Something great for me would be to have two buttons. "Create redirects" and "Create redirects and delete from error logs". Looks like the second name is a bit long.

**Comment by adrenth** [comment]
Finished first implementation and released it in version 2.0.3
