### ISSUE TITLE
Redirections using HTTPS

### ISSUE THREAD

**Issue by alvaro-canepa** [adrenth/redirect#26]
Using `http` the redirection is right updated, but when use `https` the redirection wasn't updated.

**Comment by adrenth** [comment]
Please can you provide more context to this issue?

**Comment by alvaro-canepa** [comment]
Forget this, The redirections work fine. But, if the website use https, and update a redirection, The new redirection takes a while to be seen. In my case, I have a redirection from home "/" to "/login", after a time, I need to update to "/about" and it be reflected immediately using insecure website `http://www.demo.com` but takes a long time (hours I think) using secure website `https://www.demo.com`.

I don't know if this is a browser cache problem, server or something with the SSL protocol. But is not with your plugin ;)

Thanks and sorry for the false issue.
