### ISSUE TITLE
Issue with migration

### ISSUE THREAD

**Issue by Nks** [adrenth/redirect#28]
Clear installation.
Last version of octobercms.
When it's trying to install plugin retrieving error:
```
Update failed

"SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'timestamp' (SQL: create table `adrenth_redirect_clients` (`id` int unsigned not null auto_increment primary key, `redirect_id` int unsigned not null, `timestamp` timestamp default 0 not null, `day` tinyint unsigned not null, `month` tinyint unsigned not null, `year` smallint unsigned not null, `crawler` varchar(255) null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)" on line 662 of /home/vagrant/Code/october.dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

I think this issue already fixed in by this https://github.com/adrenth/redirect/issues/23 but it seems octobercms have old code and not updated it. Any chance how can I fix this?

**Comment by adrenth** [comment]
Hi Nks,

It is definitely related to issue #23. Please follow these steps.

1. Perform a fresh install of OctoberCMS and adjust your database settings in `config/database.php`
2. Add this line of code to `config/database.php` in the `'mysql'` section: `'strict' => false,` (should be near line 64).
3. Install the plugin: `php artisan plugin:install Adrenth.Redirect` (or within the CMS)

This should work fine.

I've tested it with PHP 5.6.26 and MySQL 5.7.15.

Please let me know if this works for you.

**Comment by Nks** [comment]
@adrenth yes, I know about strict option :) Yes, it's working, but I mean that the #23 not applied to a live version on octobercms.

BTW for a last version all working correctly! Thanks for updates :)
