### ISSUE TITLE
Support multi server environments

### ISSUE THREAD

**Issue by pfyod** [adrenth/redirect#3]
We are running OctoberCMS on multiple servers. Unfortunately, this plugin does not really support this deployment scenario out of the box, as it caches redirect rules inside the hardcoded 'app/redirects.csv' file. One can fiddle with NFS / inotify + rsync / etc to distribute this file between nodes, but I don't believe that it's an optimal solution.

There are obviously multiple ways how this can be implemented:

- Automatically publish the 'app/redirects.csv' if file modification date is older than the newest change in the database (requires a DB query inside RedirectManager::loadRedirectRules);
- Allow publishing into cache instead of the 'app/redirects.csv'. That way one can have a centralized / clustered / replicated Redis setup and cache rules get automatically shared between servers;
- Allow disabling 'app/redirects.csv' altogether to always read redirect rules from the database.

**Comment by adrenth** [comment]
Moved to: https://github.com/vdlp/oc-redirect-plugin/issues/1
