### ISSUE TITLE
Bug on delete plugin

### ISSUE THREAD

**Issue by artras** [adrenth/redirect#30]
![bug_red](https://cloud.githubusercontent.com/assets/5288244/19411345/b3bb4022-9308-11e6-9472-54742aa2202b.PNG)

**Comment by adrenth** [comment]
Hey thanks for reporting this issue. But I can't reproduce this on my local machine.
Which version of PHP (looks like php7) and MySQL are you using?

**Comment by artras** [comment]
5.6.33 - MySQL Community Server (GPL)
7.0 - ea-php70 on WHM

**Comment by adrenth** [comment]
Cannot reproduce. Closing this issue for now.
