### ISSUE TITLE
Little help pls with your plugin or maybe it's a bug?

### ISSUE THREAD

**Issue by ayumihamsaki** [adrenth/redirect#37]
Hi,

First off, this plugin is amazing. Second I have seen in the last few days so many updates to this plugin. So big thank you for all your hard work.

Ok on to my problem I am trying to create this set of redirects in October CMS to try and keep the home/index page clean. Redirects I am trying to setup are as follows:

```
RewriteRule ^home.html https://www.example.com [R=301,L]
RewriteRule ^index.html https://www.example.com [R=301,L]
RewriteRule ^home.php https://www.example.com [R=301,L]
RewriteRule ^index.php https://www.example.com [R=301,L]
```

(sorry I write it in HTaccess style for you)

My problem is how do I redirect to the homepage in your plugin? I have tried redirecting these four things to:

`/
and
https://www.example.com`

In the "Target Path or URL".

But not working? Any ideas how to achieve this thanks.

**Comment by adrenth** [comment]
Hi Ayumi,

From your examples you could make these (working) redirects:

Source path: /home.htm
Target path: /

Source path: /index.htm
Target path: /

Source path: /home.htm
Target path: /

Source path: /index.htm
Target path: /

Source path: /home.php
Target path: /

I'm not sure this fixes your problem, maybe you can paste (a part of) your `redirects.csv` from `/storage/app/redirects.csv`?

**Comment by ayumihamsaki** [comment]
Perfect I had a large coffee and followed your advice and managed to redirect all of these:

```
/home.html
/home.htm
/home.php
/home
/home/

/index.html
/index.htm
/index.php
/index
/index/
```

Ok this brings me on to the next subject. I would like to be able to strip all the .html .htm and .php extensions from the URL's and redirect them, for example:

`https://www.example.com/filename.html
redirects to
https://www.example.com/filename`

I have the code for the HTaccess I can share with you that can do this. It would be nice to have a few buttons in your plugin that can turn off each of these extensions.

(Just trying to keep the website clean and tidy as I know some users will try and write the URL extensions and right now the website will hit them with a 404 error screen instead of redirecting them.

Thank you for your quick reply and if possible let me know if this idea would be useful to your plugin? I don't mind sending you the code for it.

**Comment by adrenth** [comment]
I hope you enjoyed your coffee, time for to the next cup. Now, create a new redirect and set the `Match Type` to: `Placeholders`.

Source Path: `/filename.{extension}`
Target Path: `/filename`

And for the requirements of this particular placeholder you can do something like this:

![image](https://cloud.githubusercontent.com/assets/5699988/20650878/66e74564-b4d9-11e6-99a3-8e47d6e0c974.png)

You can test the redirect as such:

![image](https://cloud.githubusercontent.com/assets/5699988/20650896/ed3c3002-b4d9-11e6-99ce-8ee88f868cd9.png)

Please let me know if this works for you.

**Comment by ayumihamsaki** [comment]
Ah I see now when you set the _Match Type_ to: _Placeholders_ then the Requirements appears! hehe

Perfect managed to achieve this, many thanks for your help.

Before I thought this was an amazing plugin, now I am totally blown away at all the features. 

Many Thanks, feel free to close this issue...

**Comment by adrenth** [comment]
No problem! I'm happy to help. Please feel free to leave a comment on octobercms.com and rate my plugin.

If you have any questions, you know where to find me.
