### ISSUE TITLE
Question: What's the regex to set everything in Requirement?

### ISSUE THREAD

**Issue by ayumihamsaki** [adrenth/redirect#43]
Hi,

Got a very easy question for you.

I have a placeholder called {extension} and I want the Requirement to select everything. All letters lower and upper case all numbers and all special characters (everything).

Have tried several regex and not succeeded yet, so I thought I'd ask you.

Found answer just need to add .*

**Comment by ayumihamsaki** [comment]
Found answer just need to add .*

**Comment by adrenth** [comment]
Hi ayumihamsaki,

That's correct! Although the field **Requirement** marks that it is a mandatory field, you can leave it empty (OMG! ;)). As you can see it will accept any value for the placeholder `{extension}`.

Thanks for using my plugin, if you like my plugin, please leave a comment/rating on octobercms.com.

~ Alwin
