### ISSUE TITLE
SQLite compatibility problem in 2.0.18

### ISSUE THREAD

**Issue by jan-vince** [adrenth/redirect#46]
After last update to 2.0.18, I have this SQLite error:

```
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such function: CURDATE' in ...
```

The problem is in `Adrenth\Redirect\Controllers\Statistics` class in methods:

* getTopTenCrawlersThisMonth()
* getTopTenRedirectsThisMonth()

I was able to fix this by changing raw queries from `->whereRaw` to:

```
->whereYear('timestamp', '=', date('Y'))
->whereMonth('timestamp', '=', date('m'))
```

*There should be [date('m')](http://laraveldaily.com/eloquent-date-filtering-wheredate-and-other-methods/) in this case.*

Can you please check this also in MySQL?

Thank you,
Jan

**Comment by adrenth** [comment]
OMG! You are right, this could work with SQLite but MySQL has no results on this one. I'll look into it...
