### ISSUE TITLE
[Feature request] Code 410

### ISSUE THREAD

**Issue by jan-vince** [adrenth/redirect#47]
Sometimes I need to return code 410 (gone).

It would be great if I can handle this with redirect plugin, so I can keep all this stuff at one place.

*Even though 410 is not a redirect :)*

Jan

**Comment by adrenth** [comment]
The plugin already supports a 404, so a 410 would'nt be much trouble to add 😜 And I think that other users may use this status code too.

**Comment by jan-vince** [comment]
Thanks :)

**Comment by adrenth** [comment]
Released in 2.0.20! Keep them requests coming ;-)
