### ISSUE TITLE
Feature Request: 303 Semantic Web Redirect

### ISSUE THREAD

**Issue by ayumihamsaki** [adrenth/redirect#48]
Hi,

Just seen you added a 410, so I thought I write this post and ask for a 303 redirect. We use it for adding Web 3.0 Semantic features to websites and 303 a URI. See here: https://en.wikipedia.org/wiki/HTTP_303

Anyway, it would be useful to add this feature to your plugin. Personally I think I use these 3xx redircts: 301, 302, 303, 305 and 307. All the rest I would not worry about.

p.s. I have already added a good review, but I honestly think your plugin is the best one in October CMS. I would love to see you create some more plugins. One easy one that I think of, would be to add htmlpurifier to October and would be easy to code up in no time at all. See here: http://htmlpurifier.org/

Anyway, big thank you for the plugin and love watching it getting updates all the time and seeing all the new features.

**Comment by adrenth** [comment]
I love to hear it that you like my plugin. I create a lot of plugins, but those are not open source unfortunately. But all ideas are welcome. If you need anything specific, feel free to contact me. Maybe you can send me more details about the html purifier plugin idea? 

Anyway, back to the 303. It seems resonable to me to add this one as well 😀 I really don't see why I should not.

Thanks for your request, this feature will be added this week.

**Comment by ayumihamsaki** [comment]
Many thanks for your reply. Let me know how to contact you properly and I can explain a bit more about the htmlpurifier plugin idea. The reason I suggest this idea is because October CMS uses html_clean() but this doesn't work for many html things (like youtube iframes etc) to protect from XSS attacks. So using htmlpurifier would protect people from a much wider selection. 

I saw you only had 2 plugins there and thought this plugin would be a quick way for you to disturb another great plugin which I know almost every October CMS user really needs right now.

html_clean() = https://octobercms.com/docs/markup/function-html
htmlpurifier = http://htmlpurifier.org/

**Comment by adrenth** [comment]
You can contact me at adrenth at gmail dot com.

**Comment by ayumihamsaki** [comment]
Thanks, I saved it, I will try and send you an email later, just in the middle of coding something,...

(if you want to delete your email comment go ahead - I don't want you to get spammed).

**Comment by adrenth** [comment]
Ok, I removed the comment ;-) 

And also released 2.0.21 which contains your request for a 303 status code. I think it should work like the RFC for HTTP/1.1 describes.
