### ISSUE TITLE
[question] Add from Request log

### ISSUE THREAD

**Issue by jan-vince** [adrenth/redirect#50]
When I add new redirect from Request log for URL with some parameters, all of them are removed.

Eg: http://www.acme.com/blog?id=1&view=grid

will be created as redirect:

http://www.acme.com/blog

Is this intended?

**Comment by adrenth** [comment]
Let's say I forgot that one ;-)

Thanks for noticing, I've added this one right away. Will be included in the next release.

**Comment by jan-vince** [comment]
Thanks :)

**Comment by adrenth** [comment]
Hmm, I see that the native `parse_url` method mixes up the params. 

E.g:

/test?z=1&a=2

becomes:

/test?a=2&z=1

I'll look into that tonight.
