### ISSUE TITLE
[Request] Schedule Redirect

### ISSUE THREAD

**Issue by DanielHitchen** [adrenth/redirect#6]
Hi,

Really nice plugin man! I've also built a little redirect plugin of my own, albeit not to the detail/level of this one, but one feature which I have built into mine which I found useful was the functionality to schedule a redirect to only be active at a certain time or between certain times - I think your plugin would benefit from the same functionality.

**Comment by adrenth** [comment]
Hi Daniel, thanks for your compliments and many thanks for you feedback! This definately a nice feature. I can imagine that SEO specialists would love this feature.

I'll look into it, and expect it to be in one of the future releases.

**Comment by adrenth** [comment]
Almost done. Hope to release it tomorrow.

**Comment by adrenth** [comment]
Will be released in 1.0.6.
