### ISSUE TITLE
Issue with migration when installing (column not found)

### ISSUE THREAD

**Issue by dogiedog** [adrenth/redirect#8]
Don't have the time to look into this but the error message is:

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'publish_status' in 'field list' (SQL: insert into `adrenth_redirect_redirects` (`match_type`, `from_url`, `to_url`, `test_url`, `sort_order`, `is_enabled`, `is_published`, `status_code`, `publish_status`, `updated_at`, `created_at`) values (exact, /example/source/path, /example/target/path, /example/source/path, 99990, 0, 0, 301, 0, 2016-04-03 15:26:44, 2016-04-03 15:26:44))" on line 624 of /x/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Try again`

**Comment by adrenth** [comment]
Bloody seeders :-) Can you try installing 1.0.9?
It seems that seeders are executed in a different order...

**Comment by dogiedog** [comment]
Fixed it :)
